default: &default
  adapter: postgresql
  url:  postgres://postgres:@localhost:5432/falcon_test
  pool: 200
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
